sevenfacette:
  http:
    clients:
      restfulbooker:
        connectiontimeout: 5000
        connectionrequesttimeout: 4000
        sockettimeout: 3000
        baseurl: www.google.de/
        #urlpath: @import("")
        #port:
        protocol: https://
        #proxyhost: localhost
        #proxyport: 8080
        #authentication:
        #  type: basic
        #  username: test
        #  password: "${TEST_PW}"
      testclient:
        connectiontimeout: 5000
        connectionrequesttimeout: 4000
        sockettimeout: 3000
        baseurl: localhost
        urlpath: /
        port: 3001
        protocol: https://
  kafka:
    bootstrapserver: <bootstrapServer>
    autooffset: earliest
    sasl: true
    saslmechanism: SCRAM-SHA-256
    saslprotocol: SASL_SSL
    sasluser: <KafkaUser>
    saslpw: "${kafkaPW}"
    consumingtimeout: 5000
    consumer:
      topic1: <topicname 1>
      topic2: <topicname 2>
  web:
    browserName: chrome
    chromeBin: ""
    highlightColor: red
    highlightSize: 2px
    highlightStyle: dotted
    listenerClass: ""
    reportDir: ""
    timeout: 4000
    startMaximized: true
    autoClose: true
    screenSize:
      - 1920
      - 1080
    pollingInterval: 0.1
    baseUrl: http://juliemr.github.io/protractor-demo/
    remoteUrl: <selenium grid url>
    chromeArgs:
      - no-sandbox
---
